groups:
- name: cortez_critical
  rules:
  # Project Cortez System Health
  - alert: CortezBrianDown
    expr: up{instance="brian",project="cortez"} == 0
    for: 1m
    labels:
      severity: critical
      project: cortez
    annotations:
      summary: "Project Cortez - Brian is down"
      description: "Brian (Project Cortez main system) has been unreachable for more than 1 minute"

  - alert: CortezHighCPU
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle",instance="brian"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
      project: cortez
    annotations:
      summary: "Project Cortez - Brian CPU usage high"
      description: "Brian CPU usage is above 80% for more than 5 minutes - may impact HA/Jellyfin performance"

  - alert: CortezHighMemory
    expr: (1 - (node_memory_MemAvailable_bytes{instance="brian"} / node_memory_MemTotal_bytes{instance="brian"})) * 100 > 85
    for: 3m
    labels:
      severity: warning
      project: cortez
    annotations:
      summary: "Project Cortez - Brian memory usage high"
      description: "Brian memory usage is above 85% - may affect Docker containers"

  # AI HAT Specific Alerts
  - alert: CortezAIHatOverheat
    expr: cortez_ai_hat_temperature_celsius > 85
    for: 2m
    labels:
      severity: critical
      project: cortez
    annotations:
      summary: "Project Cortez - AI HAT overheating"
      description: "13 TOPS AI HAT temperature is critically high at {{ $value }}°C"

  - alert: CortezAIHatHighUtil
    expr: cortez_ai_hat_utilization_percent > 95
    for: 10m
    labels:
      severity: warning
      project: cortez
    annotations:
      summary: "Project Cortez - AI HAT high utilization"
      description: "AI HAT utilization has been above 95% for 10 minutes"

  # Home Assistant Alerts
  - alert: CortezHomeAssistantDown
    expr: cortez_ha_response_time_seconds == -1
    for: 2m
    labels:
      severity: critical
      project: cortez
    annotations:
      summary: "Project Cortez - Home Assistant down"
      description: "Home Assistant is not responding to API requests"

  - alert: CortezHomeAssistantSlow
    expr: cortez_ha_response_time_seconds > 5
    for: 3m
    labels:
      severity: warning
      project: cortez
    annotations:
      summary: "Project Cortez - Home Assistant slow"
      description: "Home Assistant API response time is {{ $value }}s"

  # Jellyfin Alerts
  - alert: CortezJellyfinDown
    expr: cortez_jellyfin_response_time_seconds == -1
    for: 2m
    labels:
      severity: warning
      project: cortez
    annotations:
      summary: "Project Cortez - Jellyfin down"
      description: "Jellyfin media server is not responding"

  # UPS Power Alerts
  - alert: CortezUPSBatteryLow
    expr: cortez_ups_battery_percent < 20
    for: 1m
    labels:
      severity: critical
      project: cortez
    annotations:
      summary: "Project Cortez - UPS battery low"
      description: "UPS battery is at {{ $value }}% - prepare for potential shutdown"

  - alert: CortezUPSHighLoad
    expr: cortez_ups_load_percent > 80
    for: 5m
    labels:
      severity: warning
      project: cortez
    annotations:
      summary: "Project Cortez - UPS high load"
      description: "UPS load is {{ $value }}% - monitor power consumption"

  # Security Alerts  
  - alert: CortezSecurityBreach
    expr: cortez_fail2ban_banned_ips > 5
    for: 1m
    labels:
      severity: warning
      project: cortez
    annotations:
      summary: "Project Cortez - Multiple IPs banned"
      description: "Fail2Ban has banned {{ $value }} IPs - possible attack"

  # Container Health
  - alert: CortezContainerDown
    expr: up{role="containers",project="cortez"} == 0
    for: 2m
    labels:
      severity: warning
      project: cortez
    annotations:
      summary: "Project Cortez - Container monitoring down"
      description: "Cannot monitor Docker containers - cAdvisor may be down"

  # Thermal Management
  - alert: CortezCriticalTemperature
    expr: node_thermal_zone_temp{instance="brian"} > 75
    for: 2m
    labels:
      severity: critical
      project: cortez
    annotations:
      summary: "Project Cortez - Critical temperature"
      description: "Brian system temperature is {{ $value }}°C - check cooling"