
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'monitor-host'
    static_configs:
      - targets: ['node-exporter-host:9100']
        labels:
          instance: 'monitor-host'
          role: 'monitoring'

  - job_name: 'cortez-brian-system'
    static_configs:
      - targets: ['192.168.1.133:9100']
        labels:
          instance: 'brian'
          role: 'system'
          project: 'cortez'
