# Prometheus configuration file for roundrock-home-stack
# Save this as: svc-prometheus/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'roundrock-home-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # AlertManager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

  #Pihole64 Metrics (if applicable)
  - job_name: 'pihole6'
    static_configs:
    - targets: ['192.168.1.20:9666']

  # Docker daemon metrics (if enabled)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    metrics_path: /metrics

  # Macbook Pro M3 metrics (if applicable)
  - job_name: 'macbook-metrics'
    static_configs:
      - targets: ['192.168.1.194:9100']
    scrape_interval: 30s
    metrics_path: /metrics  

  # RPiCortex AI Engine Metrics
  - job_name: 'rpicortex-ai'
    static_configs:
      - targets: ['192.168.1.133:9103']
    scrape_interval: 15s

  # KUMA Metrics
  - job_name: 'uptime-kuma'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.20:3005']

  # NETDATA Metrics
  - job_name: 'netdata'
    metrics_path: /api/v1/allmetrics
    params: { format: [prometheus] }
    static_configs:
      - targets: ['192.168.1.20:19999']

  # BLACKBOS_ICMPP Metrics
  - job_name: 'blackbox_icmp'
    metrics_path: /probe
    params: { module: [icmp_ipv4] }
    static_configs:
      - targets: ['1.1.1.1','8.8.8.8','192.168.1.254']
    relabel_configs:
      - source_labels: [__address__]  # send the target as a param
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '192.168.1.20:9115'