version: '3.8'

services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: ${HA_TIMEZONE}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    volumes:
      - ${CONFIG_DIR}/pihole/etc-pihole:/etc/pihole
      - ${CONFIG_DIR}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped