version: '3.8'

services:
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    ports:
      - "9617:9617"
    environment:
      - PIHOLE_HOSTNAME=localhost
      - PIHOLE_PORT=80
      - PIHOLE_PASSWORD=${PIHOLE_PASSWORD}
      - INTERVAL=30s
    restart: unless-stopped

networks:
  default:
    driver: bridge