
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@roundrock-home.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-notifications'

receivers:
- name: 'default-notifications'
  webhook_configs:
  - url: 'http://localhost:5001/alerts'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
